### ISSUE TITLE
Emoji/Gif/Sticker picker missing on server channels

### ISSUE THREAD

**Issue by piebaker** [discord-extensions/bubble-bar#7]
When interacting with servers, the GIF/emoji/sticker picker is missing. It is present in DM's, however. Tested with only bubble-bar enabled. 

Server:
![image](https://user-images.githubusercontent.com/73162560/190348385-1eac7c05-2e43-4921-bd8b-bd4c4b537c6f.png)

DM:
![image](https://user-images.githubusercontent.com/73162560/190348442-010d7a0a-6f02-45fc-b6f4-5a0be569dc14.png)

This may be a recent update, as it was not previously an issue. 
Looking forward to having this back!

**Comment by LuckFire** [comment]
I'm not too sure what would be causing this. It's not occurring for me either, so I can't really check. I'll leave this issue open for the time being cause it may be due to an experimental thing.

**Comment by Loremly** [comment]
Maybe u dont have permission for emojis anymore

**Comment by LuckFire** [comment]
I was thinking this but.. it should appear in general cause the server can only disable external emojis, not global ones.

**Comment by Loremly** [comment]
true true... you think any plugins or css snippets could cause this?? what OS are they using?, which client branch
so many attributes

**Comment by Loremly** [comment]
make issue template so you know everything about the users info

**Comment by LuckFire** [comment]
If anything were to cause it, it'd be a plugin. AFAIK there's no specific html / classes for just the DM's text area, and there's probably no build currently released where the emoji picker just randomly disappears (I used two different builds, I would've noticed it).

I'll hopefully make an issue template for stuff in the future, as for right now I don't really care about it that much.

**Comment by Loremly** [comment]
im black

**Comment by Loremly** [comment]
sorry

**Comment by LuckFire** [comment]
i- ok

**Comment by fedeericodl** [comment]
You can replicate this issue on a text-in-voice channel, posts in forums and threads (all in split view). However I don't think that's what he meant as from the screenshot I see the hashtag before the channel name.

Edit: you can find a funny text box when creating a post in forums.

**Comment by piebaker** [comment]
Just as quickly as that bug happened, it is now gone. Probably best to leave this issue open, as inconsistent bugs are still bugs. Probably a discord side thing considering it has now fixed itself

**Comment by LuckFire** [comment]
> You can replicate this issue on a text-in-voice channel, posts in forums and threads (all in split view). However I don't think that's what he meant as from the screenshot I see the hashtag before the channel name.
> 
> Edit: you can find a funny text box when creating a post in forums.

Interesting.. I'll take a look into the forum and text channels when I can :+1:

**Comment by LuckFire** [comment]
This in specific seems to be causing it.
```scss
.expression-picker-chat-input-button {
    &:not(:nth-of-type(3)) {
        display: none;
    }
    &.buttonContainer-2lnNiN:nth-of-type(3) {
        order: -1;
        position: absolute;
        left: -50px;
        .button-f2h6uQ {
            background-color: transparent;
        }
    }
}
```
Since thread channels & voice text channels dont have the gift, gif, and sticker picker, it removes the emoji button. Only best way I can fix this is by removing all of this cause I don't want to use aria-labels cause compatibility issues..

**Comment by LuckFire** [comment]
```scss
> button ~ .expression-picker-chat-input-button:not(:nth-child(4)) {
    display: none;
}
.emojiButton-3FRTuj {
    display: flex !important;
    order: -1;
    position: absolute;
    left: -50px;
    .button-f2h6uQ {
        background-color: transparent;
    }
}
```
Found a hacky solution, hopefully overall this works for threads channels and voice text channels. Will still leave this issue opened however incase.
